services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - /tmp/mosquitto/config:/etc/mosquitto
      - /tmp/mosquitto/data:/var/lib/mosquitto

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /home/kzuca/project/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

  bridge:
    build: esp32_bridge_python
    container_name: esp32-bridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - .:/project
    environment:
      BRIDGE_SRC_DIR: /project/esp32_bridge_python
      PYTHONPATH: /project/esp32_bridge_python
      MQTT_HOST: localhost
      MQTT_PORT: "1883"
      HTTP_PORT: "80"
      LOG_LEVEL: info
