services:
  esp-matter-dev:
    image: espressif/esp-matter:latest
    container_name: esp-matter-dev
    
    
    volumes:
      - C:\git\bridge:/project
      - idf_cache:/root/.espressif
    
    environment:
      - IDF_TARGET=esp32
    
    command: /bin/bash -c "export IDF_TARGET=esp32 && source /opt/espressif/esp-matter/export.sh && source /opt/espressif/esp-idf/export.sh && cd /project && tail -f /dev/null"

networks:
  esp-net:
    driver: bridge

volumes:
  idf_cache:
    name: idf_cache