#pragma once
#include <Arduino.h>

#define DEVICE_NAME "Sensor Chuva"

#define DEVICE_TYPE_RAIN 7

#define DEVICE_TYPE DEVICE_TYPE_RAIN

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD 5
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define RAIN_ANALOG_PIN A0
#define LED_PIN 2

#define RAIN_DRY_THRESHOLD 90
#define RAIN_WET_THRESHOLD 30
#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000
