#pragma once
#include <Arduino.h>

#define FW_VERSION "v0.0.11"

#define DEVICE_NAME "Sensor Presenca"

#define DEVICE_TYPE_OCCUPANCY 4

#define DEVICE_TYPE DEVICE_TYPE_OCCUPANCY

#define STATE_UPDATE_INTERVAL 1000
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define OCCUPANCY_DEBOUNCE_MS 3000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define PIR_PIN 4
#define ALARM_LED_PIN 5
#define LED_PIN 2

#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000
