#pragma once
#include <Arduino.h>

#define DEVICE_NAME "Medidor Energia"

#define DEVICE_TYPE_ELECTRICITY 11

#define DEVICE_TYPE DEVICE_TYPE_ELECTRICITY

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD 5
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define SENSOR_ANALOG_PIN A0
#define LED_PIN 2

#define AC_VREF 3.3f
#define BURDEN_RESISTOR 800.0f
#define TURNS_RATIO 2000.0f

#define SAMPLING_MS 500
#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000
