#pragma once
#include <Arduino.h>

#define DEVICE_NAME "Detector Gas"

#define DEVICE_TYPE_GAS 6

#define DEVICE_TYPE DEVICE_TYPE_GAS

#define STATE_UPDATE_INTERVAL 5000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define MQ_ANALOG_PIN A0
#define ALARM_PIN 5
#define NORMAL_PIN 4
#define LED_PIN 2

#define GAS_ALERT_THRESHOLD 10
#define GAS_ALARM_THRESHOLD 20
#define NORMAL_PULSE_MS 500
#define ALARM_BLINK_FAST_MS 200
#define ALARM_BLINK_SLOW_MS 1000
#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000
