#pragma once
#include <Arduino.h>

#define FW_VERSION "v0.0.9"
#define DEVICE_NAME "DHT + Gas"

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD_TEMP 0.5
#define STATE_SEND_THRESHOLD_HUM 3.0
#define STATE_SEND_THRESHOLD_GAS 5
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define DHT_PIN 4
#define DHT_TYPE DHT22
#define GAS_ANALOG_PIN A0
#define GAS_DIGITAL_PIN 16

#define LED_PIN 2
#define GAS_LED_ALERT_PIN 14
#define GAS_LED_ALARM_PIN 12

#define GAS_ALERT_THRESHOLD 15
#define GAS_ALARM_THRESHOLD 30
#define NORMAL_PULSE_MS 500
#define ALARM_BLINK_FAST_MS 200
#define ALARM_BLINK_SLOW_MS 1000
#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000
