FROM espressif/idf:latest

RUN apt-get update && \
    apt-get install -y && \
    apt-get clean && \
    curl -fsSL https://opencode.ai/install | bash && \
    curl -fsSL https://code-server.dev/install.sh
